
GET  http://localhost:3000/api/user/629624957e9dce686a1dd28f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjI5NjI0OTU3ZTlkY2U2ODZhMWRkMjhmIiwibmFtZSI6IkFuZHJlIFJvZHJpZ3VlcyIsImVtYWlsIjoiYW5kcmVAZ21haWwuY29tIn0sImlhdCI6MTY1NDAwNjk5OSwiZXhwIjoxNjU0MDEwNTk5fQ.rGi0HjiKyGCkjnYw5xmabwo2Ln5mH2Xy743xq_C_gjA


